---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-credentials
  namespace: app1
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgCXkpYidos8/qFaNExZSiBolJXzRyHHwztM8X1jayL/To+KWBeKg/NMFqODw4dgkENLS7Ilh6BaUbVj8qWHTXMQNke6ggZC+WB5I7NKhBVBQKvptO6l3OHIx6JGtD2galSWCR+cfDyAE8AVdBZMzdi410LJcgk8/nx7V8QhbgAihAbUJxECuNPEEA/3PbspYKGT77Fp+dYrgnKa/u0QPqjZORXVCmzoBot/pmZSHbJZ62vlP4WtT+LReRnicoN8q/5idOl8aDbTGrXypjd6MCywFKa35Ny/Ja1a7MgQ81UuQ7O/KE7z/eCY50BIxCJ92vNhxlCXFXlQF28/iM2PASF0Oh4QxZm56cjX0aOOJQWFoOTOcxaX8vrirCjm1rAuG+A1YYLB4nbetAWNILC+5GPDXX3ViXHRKT7RVSjJzXkJdq7LshB0eQRz9vNrEAxjYv2V89+dzh2RJv8nTD3ZBJvOV4RzsuTaOrvi83lIY/8Hbftp8J/sIGXuvfFT9Dw3bO7EevAS83G3hRI3EdlN/R2f6m5aL++DkjEXZgDqqF+rGjrbFuqjcZNQXC6tQSgq7fyNjgHdczXEituDz8n4qBMR8kxTbMDACgO8c8Z0WspkPwCy1xdgVJK38opcXEx2Um8eIylO+KvVKtucd4ho9v65zKdbDuzixATJmJlNgM8bJZzWpKdHLsLjqjekn0fwTfVN5OlSHOzqVDZWiOjU65T1VXM/Uw==
    AWS_SECRET_ACCESS_KEY: AgBNGT3qgmBGhZ38c1gnmKfnhfXFLCEZ04IB1AB4yTGCuvQllvhoVCbz+qYMaCskj7jt7PZSV+WA3rs3OKwvoLz7kTnMGoM9QeKnO10Y8fjRAGym0nHQt79YFZ/VHfoMA3KAjlsZLZ6lOvWm2LVsQRe5Mb1TSIwfOAs0NTKDWgYoSLpMmC7QNxrKwMbp/UjfZWuNIS7Fn4c9k44pKTb9VUHRyGxaickFCa0SeLgp9qnJ30yFumKAL4Uss66fiSycnV4m6W11L0DcQ286JUF4lqy3br4qwN1owTyo/47Qi6f6jIzx0CWj+6jZcfd+kNizQDVmcb1k4o/OaAN9UlpNIwu05DSHPYOKOu/fMnWkmcjqlt0D5oN1kUersDMlJmpsi2btcFKQR8XaWrqJypFVeC6W45VuSM+gX7DLk3NQDnoY3u9nKGnCZHC5A1TjSyCx+PRqzV4YYqcHuxOKkd40rdV/lmSV2ES6Qul5bpxBp7CuOu2q2/Gi3WMeB7zrpDS0y+mTkItXfSgtdtrfW6B0I1aqNEpVSaAtZ1soSKwa8mzW+l9aLcuy3u3dDgBNaDUpj6fHvvj+35Jx3B2q7ad7JGipMQu4Yx5flCtx+Knnrv4H/rvPDXvfgoENRmyaH9b8X+ISZd4+dFqA2iynNZaZSsX8nNg+UbqxQNRvfXGDMJOMBfT5+rqydOuV09V9Wu1cYCmmzEF0qju43XjN8dK2BPkBojCpeXxP43cJoic2Zsqj7GCS3WPpcKnP
  template:
    metadata:
      creationTimestamp: null
      name: aws-credentials
      namespace: app1
