---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: basic-auth
  namespace: app1
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgCluTTuW0bRD2bAFzGXnlccfSrMT8mTzz/zQKTQE+C58Y45eHRpHJrZlPlib/jcrll9KR4k7Qy8rY55/nvPde2dWb4fUV/GS5OSfiotXVi1p5S77xRp3bYgJ3YUAP23nuXU0JC1k0tMGeWpF/u5WcH3je9zbmZnUPga7iJVD+oSbgI7OtIzY3tR2YF6N6DiS5WTI1cNAR/LtzFeYcwg/+x9WfJWOZi+H99sjX58DX/f/tSl94kmUcUipAMojBqP+vILIrgm4Rn8xQ2cciHyUCVzMFF3rDrWsgj9zhA4iEQInFfDDqFoNkLB2MxJgxoaCbCR9iMvkkOR1aqdetje+PLig005WJGpJMDlSRENbSR3EpGQCSeiOMjwzil9VLLR/yLvbmZ1cADwxHOwfGhpyKLh9h36rMEFK7U+sPTo31u9Bor24Fg7AHDmjd75sNNT+SPYtCbMNX8ca152da13YyfI9Ihh4OmWZUAinDJbYpPK0ylZ9zds7DZwpQzPQAsPSoZNbd6EFdZ7eMrFqeRtgp0DQMxHuirUc8UUozvZhdgsEwLB7dFxHd1p8k0BG8LfcencoK0T7n2eoM3T/7h1Ppr7eQKMCwr5+Lzs/rcEDsK4SfwFDYPrd2kvfxs1AuTlWuCEDhN1QB9KcQJ6HXTUQufE31aEt9QbfMUtLIWURlcTrxwm8scF/zOM7QB9eTgX6GDTr5zW7QRjuLVp5cLlR3Hh1CYmvw==
    AWS_SECRET_ACCESS_KEY: AgBfNuJR6dJviS01zymfqHxDT63/JF1xQhBm053aCFnhz6yYcEMOsJqfAhnLNK7R8QpHxblTE6mbMRXZ4UKpTWmuk7GeYftNIUUqF8bsK/dU5+WBVuJexKxFc5Yu8ZYFXRKOPs6ZPkf6yNc2q3E9EIWxK9oyzadr8tQW+LO5PDFA0LejoFTSlYQzv0FCdHwDP3Nxa/bMlzgnXXhWmes0fFvHsoZSVx6thHjF5JActmL8GTbq/QcPBTuu3df59O5LmG+CG+ZBhJTn364VfFEsOc6+sRHoQtZ18CxbZYI5/wVYygMjhzFPc3eisWZBFQtNv69rRpxlrVNnPaWJk6UDlaMt2GdMZQvCIeqlLsBX+ADQ9CrOcEWybhvcSUf6Ly06F5GbXCvfqTg2kkpyPC7PjzoVKXVj6Do5GeO9GkE+OGGQpR/AYxK9hc52q+uDTSJ/mm5LMBO3uAq0rC/auYDDOGIWPIssS1hwiw0musqPucQVA7CYEoHIPOSA8kAmSIPaEqXZijJAObeTueIe4Ro/wrh/vB4YPM3aM8hSIkCXJSZothRBoj3VVyiZk5fYjtP188i6u6pAsU+zkruvaADbkhBf3h9tGTGN78qazSuvUld0UOXwW66OjeeVqoOavTgoxOp5nBz22p1rHzsyYBleIO2Ejh8PzYa2JdGbj1qlGuMadUvcCLNdn+R+hH8mypXp+5WlMyxenbsfCf5aaPxfKXLxFCx+8ubw+il6SQrMvHaKxPVqb1H5BE29
  template:
    metadata:
      creationTimestamp: null
      name: basic-auth
      namespace: app1
